# Generated by Django 3.1.1 on 2020-10-21 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_employeeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
