# Generated by Django 3.1.1 on 2020-10-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20201021_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='todos.employeeinfo'),
        ),
    ]
