# Generated by Django 3.1.1 on 2020-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20201021_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
